// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: rank_api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankKey   string `protobuf:"bytes,1,opt,name=rankKey,proto3" json:"rankKey,omitempty"`
	Me        string `protobuf:"bytes,2,opt,name=me,proto3" json:"me,omitempty"`
	BeginRank uint32 `protobuf:"varint,3,opt,name=beginRank,proto3" json:"beginRank,omitempty"`
	Count     uint32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetRankReq) Reset() {
	*x = GetRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankReq) ProtoMessage() {}

func (x *GetRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_rank_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankReq.ProtoReflect.Descriptor instead.
func (*GetRankReq) Descriptor() ([]byte, []int) {
	return file_rank_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetRankReq) GetRankKey() string {
	if x != nil {
		return x.RankKey
	}
	return ""
}

func (x *GetRankReq) GetMe() string {
	if x != nil {
		return x.Me
	}
	return ""
}

func (x *GetRankReq) GetBeginRank() uint32 {
	if x != nil {
		return x.BeginRank
	}
	return 0
}

func (x *GetRankReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRankResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankItem []*RankItem `protobuf:"bytes,1,rep,name=rankItem,proto3" json:"rankItem,omitempty"`
	Me       *RankItem   `protobuf:"bytes,2,opt,name=me,proto3" json:"me,omitempty"`
	Total    int64       `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetRankResp) Reset() {
	*x = GetRankResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankResp) ProtoMessage() {}

func (x *GetRankResp) ProtoReflect() protoreflect.Message {
	mi := &file_rank_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankResp.ProtoReflect.Descriptor instead.
func (*GetRankResp) Descriptor() ([]byte, []int) {
	return file_rank_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetRankResp) GetRankItem() []*RankItem {
	if x != nil {
		return x.RankItem
	}
	return nil
}

func (x *GetRankResp) GetMe() *RankItem {
	if x != nil {
		return x.Me
	}
	return nil
}

func (x *GetRankResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RankItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score   int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Rank    uint32 `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	OldRank uint32 `protobuf:"varint,4,opt,name=oldRank,proto3" json:"oldRank,omitempty"`
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_rank_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_rank_api_proto_rawDescGZIP(), []int{2}
}

func (x *RankItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RankItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankItem) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankItem) GetOldRank() uint32 {
	if x != nil {
		return x.OldRank
	}
	return 0
}

var File_rank_api_proto protoreflect.FileDescriptor

var file_rank_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x6a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x6f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2a, 0x0a, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x61, 0x6e, 0x6b, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a,
	0x02, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x61, 0x6e, 0x6b,
	0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x02, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x22, 0x5e, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x6c, 0x64,
	0x52, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6f, 0x6c, 0x64, 0x52,
	0x61, 0x6e, 0x6b, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rank_api_proto_rawDescOnce sync.Once
	file_rank_api_proto_rawDescData = file_rank_api_proto_rawDesc
)

func file_rank_api_proto_rawDescGZIP() []byte {
	file_rank_api_proto_rawDescOnce.Do(func() {
		file_rank_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_rank_api_proto_rawDescData)
	})
	return file_rank_api_proto_rawDescData
}

var file_rank_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rank_api_proto_goTypes = []interface{}{
	(*GetRankReq)(nil),  // 0: rank.GetRankReq
	(*GetRankResp)(nil), // 1: rank.GetRankResp
	(*RankItem)(nil),    // 2: rank.RankItem
}
var file_rank_api_proto_depIdxs = []int32{
	2, // 0: rank.GetRankResp.rankItem:type_name -> rank.RankItem
	2, // 1: rank.GetRankResp.me:type_name -> rank.RankItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rank_api_proto_init() }
func file_rank_api_proto_init() {
	if File_rank_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rank_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rank_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rank_api_proto_goTypes,
		DependencyIndexes: file_rank_api_proto_depIdxs,
		MessageInfos:      file_rank_api_proto_msgTypes,
	}.Build()
	File_rank_api_proto = out.File
	file_rank_api_proto_rawDesc = nil
	file_rank_api_proto_goTypes = nil
	file_rank_api_proto_depIdxs = nil
}
